export OPENCV_OPENCL_DEVICE='TI AM57:ACCELERATOR:TI Multicore C66 DSP'
export TI_OCL_LOAD_KERNELS_ONCHIP=Y
export TI_OCL_KEEP_FILES=Y
export TI_OCL_CACHE_KERNELS=Y
export TARGET_ROOTDIR=/
./umat2mat im2.png im6.png

